### status
GET http://localhost:3000/api/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTY1NDRhNjU0YTkzYzBjMDljZjE0OCIsImlhdCI6MTY1NTA3MDEyNiwiZXhwIjoxNjU1MTU2NTI2fQ.AOcIegpKdHyHZWTLNS7RIpyNpCw8wccZpklJT1ZfETM
###
### agendamento getAll
GET  http://localhost:3000/api/agendamento 
###
### agendamento getOne
GET  http://localhost:3000/api/agendamento/629e97fc81f5813186d60242
###
### agendamento post
POST http://localhost:3000/api/agendamento 
Content-Type: application/json

{
    "scheduleDatetreatment": "2022-05-06",
    "scheduleTime": "13:00:00",
    "scheduleSession": 32
}
###
### agendamento patch
PATCH http://localhost:3000/api/agendamento/629e97fc81f5813186d60242
Content-Type: application/json

{
    "scheduleDatetreatment": "2022-05-30",
    "scheduleTime": "20:00:00",
    "scheduleSession": 32
}
###
### agendamento delete
DELETE http://localhost:3000/api/agendamento/629e97fc81f5813186d60242
###