### status
GET http://localhost:3000/api/status
###
### fisioterapeuta getAll
GET http://localhost:3000/api/fisioterapeuta
###
### fisioterapeuta getOne
GET http://localhost:3000/api/fisioterapeuta/629e96c9be638658a42f752b
###
### fisioterapeuta post
POST http://localhost:3000/api/fisioterapeuta 
Content-Type: application/json

{
    "physiotherapistName": "Anderson Carvalho Giusti",
    "physiotherapistAge": 32,
    "physiotherapistCpf": 37593539830,
    "physiotherapistAddress": "Avenida Odair Santanelli",
    "physiotherapistNumber": 990,
    "physiotherapistComplement": "Bloco 15 Apto B14",
    "physiotherapistCity": "Guarulhos",
    "physiotherapistState": "SP"
}

###
### fisioterapeuta patch
PATCH http://localhost:3000/api/fisioterapeuta/629e96c9be638658a42f752b
Content-Type: application/json

{
    "physiotherapistName": "Anderson Carvalho Giusti",
    "physiotherapistAge": 32,
    "physiotherapistCpf": 37593539830,
    "physiotherapistAddress": "Avenida Odair Santanelli",
    "physiotherapistNumber": 990,
    "patientComplement": "Bloco 15 Apto B14",
    "physiotherapistComplement": "hauiahiauhaiuahi",
    "physiotherapistState": "SP"
}
###
### fisioterapeuta delete
DELETE http://localhost:3000/api/fisioterapeuta/629e96c9be638658a42f752b
###