### status
GET http://localhost:3000/api/status
###
### paciente getAll
GET http://localhost:3000/api/paciente
###
### paciente getOne
GET http://localhost:3000/api/paciente/629e970dbe638658a42f7533
###
### paciente post
POST http://localhost:3000/api/paciente 
Content-Type: application/json

{
    "patientName": "Anderson Carvalho Giusti",
    "patientAge": 32,
    "patientCpf": 37593539830,
    "patientAddress": "Avenida Odair Santanelli",
    "patientNumber": 990,
    "patientComplement": "Bloco 15 Apto B14",
    "patientCity": "Guarulhos",
    "patientState": "SP"
}

###
### paciente patch
PATCH http://localhost:3000/api/paciente/629e970dbe638658a42f7533
Content-Type: application/json

{
    "patientName": "Anderson Carvalho Giusti",
    "patientAge": 32,
    "patientCpf": 37593539830,
    "patientAddress": "Avenida Odair Santanelli",
    "patientNumber": 990,
    "patientComplement": "Bloco 15 Apto B14",
    "patientCity": "aaaaaaaaaaaaaaaaaaaaaaaa",
    "patientState": "SP"
}
###
### paciente delete
DELETE http://localhost:3000/api/paciente/629e970dbe638658a42f7533
###