### status
GET http://localhost:3000/api/status
###
### agendamento getAll
GET  http://localhost:3000/api/agendamento 
###
### agendamento getOne
GET  http://localhost:3000/api/agendamento/629d039a87800cb12c8c81f0
###
### agendamento post
POST http://localhost:3000/api/agendamento 
Content-Type: application/json

{
    "scheduleDatetreatment": "2022-05-06",
    "scheduleTime": "13:00:00",
    "scheduleSession": 32
}
###
### agendamento patch
PATCH http://localhost:3000/api/agendamento/629d039a87800cb12c8c81f0
Content-Type: application/json

{
    "scheduleDatetreatment": "2022-05-30",
    "scheduleTime": "16:00:00",
    "scheduleSession": 32
}
###
### agendamento delete
DELETE http://localhost:3000/api/agendamento/629d039a87800cb12c8c81f0
###