### status
GET http://localhost:3000/api/status
###
### prontuario getAll
GET http://localhost:3000/api/prontuario
###
### prontuario getOne
GET http://localhost:3000/api/prontuario/629b9a5cf6c90ef6c0174655
###
### prontuario post
POST http://localhost:3000/api/prontuario 
Content-Type: application/json

{
    "treatment": "Fim do tratamento paciente wwwwwwwwwwwwwww"
}

###
### prontuario patch
PATCH http://localhost:3000/api/prontuario/629b9a5cf6c90ef6c0174655
Content-Type: application/json

{
    "treatment": "alteradooooooooooooooooooooooooooooooooo "
}
###
### prontuario delete
DELETE http://localhost:3000/api/prontuario/629b9a5cf6c90ef6c0174655
###